replicaCount: 1

image:
  registry: "ghcr.io"
  repository: ""            # наприклад: "AnatoliiShara/my-first-telegram-bot"
  tag: "v1.0.0-SNAPSHOT"    # CI оновить на v1.0.0-<shortsha>
  os: "linux"
  arch: "amd64"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

# токен для телеграм бота, у проді краще через зовн. secret manager
teleToken: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
