name: CI/CD (build, push, update helm)

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: write       # щоб комітити назад зміну values.yaml
  packages: write       # щоб пушити в ghcr.io

env:
  VERSION: v1.0.0
  OS: linux
  ARCH: amd64
  REGISTRY: ghcr.io

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Derive variables
        id: vars
        run: |
          SHORTSHA=${GITHUB_SHA::7}
          echo "SHORTSHA=$SHORTSHA" >> $GITHUB_OUTPUT
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          OWNER="${GITHUB_REPOSITORY_OWNER}"
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "OWNER=$OWNER" >> $GITHUB_OUTPUT
          IMG_REPO="${{ env.REGISTRY }}/${OWNER}/${REPO_NAME}"
          TAG="${{ env.VERSION }}-$SHORTSHA"
          FULL_TAG="${IMG_REPO}:${TAG}-${{ env.OS }}-${{ env.ARCH }}"
          echo "IMG_REPO=$IMG_REPO" >> $GITHUB_OUTPUT
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "FULL_TAG=$FULL_TAG" >> $GITHUB_OUTPUT
          echo "Full image: $FULL_TAG"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (linux/amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.vars.outputs.FULL_TAG }}

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Update helm/values.yaml
        run: |
          yq -i '
            .image.registry = "${{ env.REGISTRY }}" |
            .image.repository = "${{ steps.vars.outputs.OWNER }}/$(basename $(pwd))" |
            .image.tag = "${{ env.VERSION }}-${{ steps.vars.outputs.SHORTSHA }}" |
            .image.os = "${{ env.OS }}" |
            .image.arch = "${{ env.ARCH }}"
          ' helm/values.yaml
          echo "Updated values.yaml:"
          cat helm/values.yaml

      - name: Commit updated values.yaml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ci): set image tag to ${{ env.VERSION }}-${{ steps.vars.outputs.SHORTSHA }}"
          branch: develop
          file_pattern: helm/values.yaml

      - name: Expose built image tag (job summary)
        run: |
          echo "Image: \`${{ steps.vars.outputs.FULL_TAG }}\`" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.vars.outputs.FULL_TAG }}" > image.txt
        shell: bash
      - name: Upload artifact (image tag)
        uses: actions/upload-artifact@v4
        with:
          name: built-image
          path: image.txt
