name: CI/CD (build, push, update helm)

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: write   # коміт назад у репозиторій (values.yaml)
  packages: write   # пуш у ghcr.io

env:
  VERSION: v1.0.0
  OS: linux
  ARCH: amd64
  REGISTRY: ghcr.io

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Derive variables (lowercase repo/owner, replace "_"->"-")
        id: vars
        shell: bash
        run: |
          SHORTSHA="${GITHUB_SHA::7}"
          OWNER="$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')"
          REPO_NAME_RAW="${GITHUB_REPOSITORY##*/}"
          REPO_NAME="$(echo "${REPO_NAME_RAW}" | tr '[:upper:]' '[:lower:]' | tr '_' '-')"

          echo "SHORTSHA=${SHORTSHA}"          >> "$GITHUB_OUTPUT"
          echo "OWNER=${OWNER}"                >> "$GITHUB_OUTPUT"
          echo "REPO_NAME=${REPO_NAME}"        >> "$GITHUB_OUTPUT"

          IMG_REPO="${REGISTRY}/${OWNER}/${REPO_NAME}"
          TAG="${VERSION}-${SHORTSHA}"
          FULL_TAG="${IMG_REPO}:${TAG}-${OS}-${ARCH}"

          echo "IMG_REPO=${IMG_REPO}"          >> "$GITHUB_OUTPUT"
          echo "TAG=${TAG}"                    >> "$GITHUB_OUTPUT"
          echo "FULL_TAG=${FULL_TAG}"          >> "$GITHUB_OUTPUT"

          echo "Full image will be: ${FULL_TAG}"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.vars.outputs.OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (linux/amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.vars.outputs.FULL_TAG }}

      - name: Install yq
        shell: bash
        run: |
          sudo wget -qO /usr/local/bin/yq \
            https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Update helm/values.yaml with new image tag
        shell: bash
        run: |
          yq -i '
            .image.registry = strenv(REGISTRY) |
            .image.repository = "${{ steps.vars.outputs.OWNER }}/${{ steps.vars.outputs.REPO_NAME }}" |
            .image.tag = "${{ env.VERSION }}-${{ steps.vars.outputs.SHORTSHA }}" |
            .image.os = strenv(OS) |
            .image.arch = strenv(ARCH)
          ' helm/values.yaml
          echo "Updated values.yaml:"
          cat helm/values.yaml

      - name: Commit updated values.yaml back to develop
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ci): set image tag to ${{ env.VERSION }}-${{ steps.vars.outputs.SHORTSHA }}"
          branch: develop
          file_pattern: helm/values.yaml

      - name: Summarize image tag
        shell: bash
        run: |
          echo "Image: \`${{ steps.vars.outputs.FULL_TAG }}\`" >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.vars.outputs.FULL_TAG }}"
